version: '3'

services:
###> doctrine/doctrine-bundle ###
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:var/www/pathcase/
    ports:
      - 8000:8080
    networks:
      - symfony

networks:
  symfony: